### ISSUE TITLE
source is not an Object

### ISSUE THREAD

**Issue by ghost** [skygard/react-native-rte#6]
Hi,

thanks for this nice component. With RN 0.60 and Webview 5.12.1 i get this "source is not an Object" error in Android as described here:

https://github.com/react-native-community/react-native-webview/issues/428

I think importing the web file must be handled slightly different:
https://github.com/skygard/react-native-rte/blob/master/src/EditorWebViewProxy.js#L26

do you have an idea?

**Comment by jig4physics** [comment]
Still I am Getting this issue. Any solution?

**Comment by BarneyLYO** [comment]
@jig4physics with the android I think you should use { uri: 'file:///path/to/editor.html' } to get the resource

**Comment by ghost** [comment]
i end up forking it, anyhow great component
